# Generated by Django 4.1.2 on 2022-10-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('departure_date', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('hours_count', models.IntegerField()),
                ('amount_paid', models.FloatField(blank=True, default=None, null=True)),
                ('booking_status', models.CharField(choices=[('active', 'active'), ('upcoming', 'upcoming'), ('past', 'past')], default='upcoming', max_length=25)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_image1', models.ImageField(upload_to='park/%Y/%B/%d/')),
                ('park_image2', models.ImageField(upload_to='park/%Y/%B/%d/')),
                ('park_image3', models.ImageField(upload_to='park/%Y/%B/%d/')),
                ('park_name', models.CharField(max_length=225)),
                ('location_cordinates', models.CharField(max_length=150, unique=True)),
                ('capacity', models.IntegerField()),
                ('available_spaces', models.IntegerField()),
                ('cost_per_hour', models.FloatField()),
                ('service_fee', models.FloatField()),
                ('discount', models.IntegerField()),
                ('park_info', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('star_ratings', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('park_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_review', to='Hackathon_app.parkingspace')),
            ],
        ),
    ]
