# Generated by Django 4.1.2 on 2022-10-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_users', '0002_alter_customuser_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_image',
        ),
    ]
